### ISSUE TITLE
How is the exercise effect of section 4.6 achieved

### ISSUE THREAD

**Issue by lzdxin** [Marius-Juston/UWB-Jackal-World#1]

**Comment by Marius-Juston** [comment]
Sorry I am confused about your question

**Comment by Marius-Juston** [comment]
Could you clarify?

**Comment by lzdxin** [comment]
dear&nbsp;Marius Juston：
Sorry for the late reply. I have already mastered the usage of the UWB-Jackal-World project. Your team's projects, such as UWB-Localization, are all excellent work. Thank you for your contributions.




Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AUVSL/UWB-Jackal-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月3日(星期二) 凌晨4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AUVSL/UWB-Jackal-World] How is the exercise effect of section 4.6 achieved (Issue #1)





 
Could you clarify?

**Comment by Marius-Juston** [comment]
Glad to hear that!
